Repository Team-Scandela/Scandela, pull requests merged in 2023-07, with the labels that each got.

#49 46 gauges elec bio lumi
  scandelapp/src/assets/gauges/bio-light.png
  scandelapp/src/assets/gauges/bio.png
  scandelapp/src/assets/gauges/elec-light.png
  scandelapp/src/assets/gauges/elec.png
  scandelapp/src/assets/gauges/left-light.png
  scandelapp/src/assets/gauges/left.png
  scandelapp/src/assets/gauges/lumi-light.png
  scandelapp/src/assets/gauges/lumi.png
  scandelapp/src/assets/gauges/middle-light.png
  scandelapp/src/assets/gauges/middle.png
  scandelapp/src/assets/gauges/right-light.png
  scandelapp/src/assets/gauges/right.png
  scandelapp/src/colors.js
  scandelapp/src/components/Gauges/elements.js
  scandelapp/src/components/Gauges/gaugesImports.ts
  scandelapp/src/components/Gauges/index.tsx
  scandelapp/src/pages/main.tsx
Labels: front end, NEW

#56 New light mode and label in french
  scandelapp/package-lock.json
  scandelapp/src/components/Map/index.tsx
Labels: front end

#64 add new docker env, with server working and jenkins removed
  docker-compose.dev.yml
  docker-compose.yml
  jenkins/Dockerfile
  jenkins/Dockerfile.dev
  jenkins/docker-compose.dev.yml
  jenkins/jenkins.yaml
  server/Dockerfile
  server/Dockerfile.dev
Labels: CI / CD

#69 [ADD]: adding 3 filters in Map component with menuFilter interaction
  scandelapp/src/components/FilterMenu/index.tsx
  scandelapp/src/components/Map/index.tsx
  scandelapp/src/components/Map/loadMap.ts
  scandelapp/src/pages/main.tsx
Labels: front end
